Repository jpbraz/catalogofilmes, pull requests merged in 2022-07, with the labels that each got.

#57 #55
  .dart_tool/package_config.json
  .dart_tool/package_config_subset
  .packages
  catalogo_filmes/lib/components/edit_playlist.dart
  catalogo_filmes/lib/components/movie_items/commentaries_info.dart
  catalogo_filmes/lib/components/movie_items/favorite_movie_item.dart
  catalogo_filmes/lib/components/movie_items/movie_card.dart
  catalogo_filmes/lib/components/movie_items/movie_info.dart
  catalogo_filmes/lib/components/movie_items/movie_menu.dart
  catalogo_filmes/lib/components/movie_items/rating_form.dart
  catalogo_filmes/lib/components/movie_items/rating_list.dart
  catalogo_filmes/lib/components/navigation/drawer.dart
  catalogo_filmes/lib/components/new_playlist.dart
  catalogo_filmes/lib/components/playlist_menu.dart
  catalogo_filmes/lib/components/playlists_list.dart
  catalogo_filmes/lib/models/playlist.dart
  catalogo_filmes/lib/models/rating.dart
  catalogo_filmes/lib/providers/catalog_provider.dart
  catalogo_filmes/lib/providers/favorites_provider.dart
  catalogo_filmes/lib/providers/playlists_provider.dart
  catalogo_filmes/lib/screens/catalog_screen.dart
  catalogo_filmes/lib/screens/details_screen.dart
  catalogo_filmes/lib/screens/favorites_screen.dart
  catalogo_filmes/lib/screens/movie_details_screen.dart
  catalogo_filmes/lib/screens/playlist_details_screen.dart
  catalogo_filmes/lib/screens/playlists_screen.dart
Labels: refactoring

#66 #58-Starting login/signup page
  catalogo_filmes/.gitignore
  catalogo_filmes/lib/components/movie_items/movie_menu.dart
  catalogo_filmes/lib/components/widgets/auth_check.dart
  catalogo_filmes/lib/components/widgets/edit_playlist.dart
  catalogo_filmes/lib/components/widgets/image_input.dart
  catalogo_filmes/lib/components/widgets/loading.dart
  catalogo_filmes/lib/components/widgets/new_playlist.dart
  catalogo_filmes/lib/components/widgets/playlist_menu.dart
  catalogo_filmes/lib/components/widgets/playlists_list.dart
  catalogo_filmes/lib/components/widgets/rating_list.dart
  catalogo_filmes/lib/main.dart
  catalogo_filmes/lib/screens/login_screen.dart
  catalogo_filmes/lib/screens/playlists_screen.dart
  catalogo_filmes/lib/services/auth_service.dart
  catalogo_filmes/lib/utils/app_routes.dart
  catalogo_filmes/pubspec.yaml
Labels: enhancement

#69 #63:Class model User. Closes #63
  catalogo_filmes/lib/models/user.dart
Labels: enhancement

#68 67 implementar as funções de login autenticação e sign up
  catalogo_filmes/.gitignore
  catalogo_filmes/README.md
  catalogo_filmes/lib/components/navigation/drawer.dart
  catalogo_filmes/lib/main.dart
  catalogo_filmes/lib/screens/login_screen.dart
  catalogo_filmes/lib/services/auth_service.dart
Labels: enhancement

#73 #72
  catalogo_filmes/lib/components/navigation/drawer.dart
  catalogo_filmes/lib/components/widgets/profile_info.dart
  catalogo_filmes/lib/screens/catalog_screen.dart
  catalogo_filmes/lib/screens/favorites_screen.dart
  catalogo_filmes/lib/screens/playlists_screen.dart
  catalogo_filmes/lib/services/auth_service.dart
  catalogo_filmes/pubspec.yaml
Labels: enhancement

#76 #74
  catalogo_filmes/lib/components/navigation/drawer.dart
  catalogo_filmes/lib/components/navigation/drawer_header_logo.dart
  catalogo_filmes/lib/components/navigation/logout_button.dart
  catalogo_filmes/lib/components/navigation/navigation_routes_buttons.dart
  catalogo_filmes/lib/components/widgets/image_input.dart
  catalogo_filmes/lib/components/widgets/profile_info.dart
  catalogo_filmes/lib/screens/login_screen.dart
  catalogo_filmes/lib/services/auth_service.dart
Labels: enhancement

#78 User on rating - firebase
  catalogo_filmes/assets/image/person-icon.png
  catalogo_filmes/lib/components/movie_items/rating_list.dart
  catalogo_filmes/lib/components/widgets/rating_list.dart
  catalogo_filmes/lib/controller/firebaseController.dart
  catalogo_filmes/lib/models/rating.dart
  catalogo_filmes/lib/models/user.dart
  catalogo_filmes/lib/services/auth_service.dart
  catalogo_filmes/pubspec.yaml
Labels: bug, enhancement
